Added Support of EntryConcatMethod
sentrysoftware/language-hdf pull request #4
Opened 2019-09-17 14:14 UTC by MarcDouguedroit

2019-09-18 17:57 UTC, bertysentry requested changes

2019-09-18 17:57 UTC, bertysentry commented on grammars/hdf.cson
> +              |executeforeachentryf
typo: missing 'o'

2019-09-19 06:31 UTC, MarcDouguedroit commented on grammars/hdf.cson
> +              |executeforeachentryf
Well spotted :)

2019-09-19 15:08 UTC, bertysentry approved these changes

2019-09-19 15:08 UTC, merged